# Generated by Django 3.2.7 on 2021-09-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emails',
        ),
    ]
