# Generated by Django 3.2.7 on 2021-10-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.TextField(max_length=500)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('mpesaVerificationCode', models.CharField(max_length=50)),
                ('amountPaid', models.IntegerField()),
                ('quantityOrdered', models.CharField(max_length=500)),
                ('Status', models.CharField(choices=[('pickedUP', 'pickedUP'), ('NotPickedUp', 'NotPickedUp')], default='NotPickedUp', max_length=20)),
            ],
        ),
    ]
