# Generated by Django 3.2.7 on 2021-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=500)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('mpesaVerificationCode', models.CharField(max_length=50)),
                ('amountPaid', models.IntegerField()),
                ('quantityOrdered', models.IntegerField()),
                ('deliveryStatus', models.CharField(choices=[('delivered', 'delivered'), ('pendingDelivery', 'pendingDelivery'), ('noDelivery', 'noDelivery')], default='pendingDelivery', max_length=20)),
            ],
        ),
    ]
