# Generated by Django 3.2.7 on 2021-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('productName', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('display_image', models.ImageField(max_length=255, upload_to='')),
            ],
        ),
    ]
